project:
  type: book

book:
  reader-mode: true
  cover-image: TCMB logo.jpeg
  cover-image-alt: The logo of the Israel Defense Forces Medical Corps Trauma and Combat Medicine Branch 
  favicon: TCMB logo.jpeg
  title: "ספר הרפואה המבצעית"
  
  page-footer:
    left: |
      ספר הרפואה המבצעית
    right: |
      אבישי צור, תומר תלמי ועפר אלמוג
  
  
  author:
  - name: 'ד"ר אבישי צור, רס"ן'
    orcid: 0000-0002-1564-6395
    url: https://avishaitsur.netlify.app/
    email: avishaitsur@gmail.com
    attributes:
      corresponding: boolean
    affiliations:
      - name: חיל הרפואה, צבא ההגנה לישראל
        url: https://en.wikipedia.org/wiki/Medical_Corps_(Israel)
        city: Ramat Gan
        state: Israel
      - name: המרכז הרפואי שיבא תל השומר
        url: https://eng.sheba.co.il/
        city: Ramat Gan
        state: Israel
  - name: 'ד"ר תומר תלמי, סרן'
    affiliations:
      - name: חיל הרפואה, צבא ההגנה לישראל
        url: https://en.wikipedia.org/wiki/Medical_Corps_(Israel)
        city: Ramat Gan
        state: Israel
  - name: 'ד"ר עפר אלמוג, סא"ל'
    affiliations:
      - name: חיל הרפואה, צבא ההגנה לישראל
        url: https://en.wikipedia.org/wiki/Medical_Corps_(Israel)
        city: Ramat Gan
        state: Israel
  date: today
  date-format: full
  site-url: https://tcmb-book.netlify.app/
  repo-url: https://github.com/avishaitsur/TCMB-Book
  repo-branch: main
  repo-actions: [edit, issue]
  chapters:
    - index.qmd
    - schema.qmd
    - safety.qmd
    - airway.qmd
    - chest.qmd
    - rdcr.qmd
    - disability_exposure.qmd
    - resucitation.qmd
    - MCE.qmd
    - loss_of_vital_signs.qmd
    - secondary_survey.qmd
    - pfc.qmd
    - pain.qmd
    - infections.qmd
    - tbi.qmd
    - eyes.qmd
    - MSK.qmd
    - pediatrics.qmd
    - vascular_access.qmd
    - crush.qmd
    - canine.qmd
    - references.qmd

bibliography: references.bib
csl: elsevier-vancouver.csl

format:
  html:
    theme: cosmo
    dir: rtl
    toc: true
    toc-title: תוכן עניינים
    number-sections: true
    number-depth: 1
    fig-width: 6.5
    fig-asp: 0.618
    fig-align: center
    fig-format: png
    fig-dpi: 300
    author-meta: "Avishai M. Tsur, Tomer Talmy, and Ofer Almog"
